# -*- coding: utf-8 -*-
"""Windows-Kennung + Startmenü-Eintrag (windows_kennung.py, JB 24.09.2026:
„Kennung + Startmenü-Eintrag").

Befund (Analyse auslieferung, Befund 3): Ohne eigene App-Kennung ordnet
Windows den pythonw-Prozess des Servers per Heuristik der einzigen
Startmenü-Verknüpfung auf pythonw.exe zu, „IDLE (Python 3.14)"
(Microsoft.AutoGenerated.{9C659DC1…}, gemessen 23.09.).

Geprüft wird das ERGEBNIS:
* die Kennung, die Windows dem Prozess danach wirklich zuschreibt (eigener
  Kindprozess, Rücklesen per GetCurrentProcessExplicitAppUserModelID);
* die Verknüpfung, wie WINDOWS sie liest (PowerShell: Shell.Application und
  WScript.Shell), nicht wie unser eigener Leser sie liest;
* die Reihenfolge in huelle.main() per Attrappe; für youtube_app.main() (zu
  groß für einen Lauf im Test) der Aufruf im Syntaxbaum — Aufruf statt
  Erwähnung, wie der Wächter „_smtc_einrichten nur in main".

JBs echtes Startmenü berührt KEIN Test: jeder Schreib-Test bekommt tmp_path,
und die Wache aus tests/conftest.py sperrt den Standard-Ordner in JEDEM Test
(laut, auch im Hintergrundfaden — geprüft in tests/test_wachen.py).
"""
import ast
import json
import os
import re
import subprocess
import sys
import types

MODUL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WURZEL = os.path.dirname(MODUL_DIR)
if MODUL_DIR not in sys.path:
    sys.path.insert(0, MODUL_DIR)

import windows_kennung as wk  # noqa: E402  (Import setzt nichts und schreibt nichts)

KENNUNG = "JBK.SyncYouTube"


def _ps(skript, **umgebung):
    """PowerShell mit UTF-8-Ausgabe; Pfade nur über die Umgebung, nie im Befehl."""
    lauf = subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-Command",
         "[Console]::OutputEncoding = [Text.Encoding]::UTF8; " + skript],
        capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=120,
        env=dict(os.environ, **umgebung),
        creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
    assert lauf.returncode == 0, lauf.stderr
    return lauf.stdout.strip()


def _windows_liest(pfad):
    """So sieht WINDOWS die Verknüpfung: Kennung über Shell.Application (die
    Eigenschaft, nach der Windows Prozess und Verknüpfung verbindet), der Rest
    über WScript.Shell. CreateShortcut auf einen vorhandenen Pfad liest nur."""
    aus = _ps(
        "$p = $env:WK_PFAD; "
        "$item = (New-Object -ComObject Shell.Application).NameSpace("
        "(Split-Path -LiteralPath $p)).ParseName((Split-Path -Leaf $p)); "
        "$l = (New-Object -ComObject WScript.Shell).CreateShortcut($p); "
        "[pscustomobject]@{kennung = $item.ExtendedProperty('System.AppUserModel.ID'); "
        "ziel = $l.TargetPath; argumente = $l.Arguments; arbeitsordner = $l.WorkingDirectory; "
        "beschreibung = $l.Description; symbol = $l.IconLocation} | ConvertTo-Json -Compress",
        WK_PFAD=str(pfad))
    return json.loads(aus)


def _fremde_verknuepfung(pfad):
    """Eine Verknüpfung, wie ein Installer oder JB sie von Hand anlegt: ohne Kennung."""
    _ps("$l = (New-Object -ComObject WScript.Shell).CreateShortcut($env:WK_PFAD); "
        "$l.TargetPath = $env:WK_ZIEL; $l.Save()",
        WK_PFAD=str(pfad), WK_ZIEL=os.path.join(os.environ["SystemRoot"], "notepad.exe"))


def _stand(pfad):
    s = os.stat(pfad)
    with open(pfad, "rb") as f:
        return (s.st_ino, s.st_mtime_ns, f.read())


def _pythonw():
    return os.path.join(os.path.dirname(sys.executable), "pythonw.exe")


# ------------------------------------------------ Was startet die Verknüpfung?

def test_quellbetrieb_startet_wie_die_bat():
    """Die Verknüpfung startet genau das, was SyncYouTube.bat startet — gemessen
    an der bat selbst (Ergebnis statt Abschrift): dasselbe pythonw, dasselbe
    Skript. Arbeitsordner ist System\\ (alle Pfade der App hängen an SCRIPT_DIR)."""
    bat = open(os.path.join(WURZEL, "SyncYouTube.bat"), encoding="utf-8").read()
    zeile = next(z for z in bat.splitlines() if z.lower().startswith("start "))
    teile = [t for t in re.findall(r'"([^"]*)"', zeile) if t]
    programm, skript = (os.path.normpath(t.replace("%~dp0", WURZEL + os.sep)) for t in teile)
    assert programm.lower().endswith("pythonw.exe") and skript.endswith("youtube_app.py"), teile
    for gestartet_mit in (programm, programm[:-len("pythonw.exe")] + "python.exe"):
        z = wk.startziel(False, gestartet_mit, MODUL_DIR)
        assert os.path.normcase(z["ziel"]) == os.path.normcase(programm), gestartet_mit
        assert z["argumente"] == f'"{skript}"'
        assert os.path.normcase(z["arbeitsordner"]) == os.path.normcase(MODUL_DIR)
        assert z["symbol"] == (z["ziel"], 0)


def test_quellstart_paket_nimmt_sein_eigenes_python():
    """Quellstart-ZIP: kein SyncDashTray-venv, sondern python\\pythonw.exe im Paket."""
    z = wk.startziel(False, r"D:\QS\python\python.exe", r"D:\QS\System")
    assert z == {"ziel": r"D:\QS\python\pythonw.exe",
                 "argumente": r'"D:\QS\System\youtube_app.py"',
                 "arbeitsordner": r"D:\QS\System",
                 "symbol": (r"D:\QS\python\pythonw.exe", 0)}


def test_exe_startet_sich_selbst():
    z = wk.startziel(True, r"D:\Apps\SyncYouTube\SyncYouTube.exe", r"C:\Temp\_MEI123")
    assert z == {"ziel": r"D:\Apps\SyncYouTube\SyncYouTube.exe", "argumente": "",
                 "arbeitsordner": r"D:\Apps\SyncYouTube",
                 "symbol": (r"D:\Apps\SyncYouTube\SyncYouTube.exe", 0)}


# ------------------------------------------------ Kennung des Prozesses

def test_kennung_wirkt_im_eigenen_prozess():
    """Eigener Kindprozess (der Testprozess bleibt unberührt): vorher hat er
    keine ausdrückliche Kennung, nach setze_kennung() liest Windows JBK.SyncYouTube."""
    code = ("import ctypes, sys; sys.path.insert(0, sys.argv[1]); import windows_kennung as w\n"
            "def lies():\n"
            "    p = ctypes.c_wchar_p()\n"
            "    hr = ctypes.windll.shell32.GetCurrentProcessExplicitAppUserModelID(ctypes.byref(p))\n"
            "    return p.value if hr == 0 else None\n"
            "vorher = lies(); ok = w.setze_kennung(); print(vorher, ok, lies())\n")
    lauf = subprocess.run([sys.executable, "-B", "-c", code, MODUL_DIR], capture_output=True,
                          text=True, timeout=60)
    assert lauf.stdout.split() == ["None", "True", KENNUNG], (lauf.stdout, lauf.stderr)


class _Shell32:
    def __init__(self, antwort=0, fehler=None):
        self.antwort, self.fehler, self.gesetzt = antwort, fehler, []

    def SetCurrentProcessExplicitAppUserModelID(self, kennung):
        if self.fehler:
            raise self.fehler
        self.gesetzt.append(getattr(kennung, "value", kennung))
        return self.antwort


def test_kennung_scheitert_still():
    """Ein Fehlschlag (Ausnahme oder Fehler-HRESULT) reißt den Start nie: False + Protokoll."""
    log = []
    gut = _Shell32()
    assert wk.setze_kennung(log=log.append, shell32=gut) is True
    assert gut.gesetzt == [KENNUNG] and log == []
    assert wk.setze_kennung(log=log.append, shell32=_Shell32(fehler=OSError("verweigert"))) is False
    assert wk.setze_kennung(log=log.append, shell32=_Shell32(antwort=-2147024809)) is False
    assert len(log) == 2 and all("Kennung" in z for z in log), log


# ------------------------------------------------ Startmenü-Eintrag (nur tmp_path)

def test_eintrag_wird_angelegt_und_windows_liest_die_kennung(tmp_path):
    log = []
    assert wk.startmenue_eintrag(ordner=str(tmp_path), log=log.append) == "angelegt", log
    pfad = tmp_path / "SyncYouTube.lnk"
    soll = wk.startziel(False, sys.executable, MODUL_DIR)
    gelesen = _windows_liest(pfad)
    assert gelesen["kennung"] == KENNUNG, gelesen
    assert os.path.normcase(gelesen["ziel"]) == os.path.normcase(_pythonw()), gelesen
    assert gelesen["argumente"] == soll["argumente"]
    assert os.path.normcase(gelesen["arbeitsordner"]) == os.path.normcase(MODUL_DIR)
    assert gelesen["beschreibung"] == wk.BESCHREIBUNG
    assert os.path.normcase(gelesen["symbol"]) == os.path.normcase(_pythonw() + ",0"), gelesen
    assert sorted(os.listdir(tmp_path)) == ["SyncYouTube.lnk"], "Zwischendatei liegen geblieben"


def test_zweiter_start_schreibt_nichts(tmp_path):
    """Idempotent: stimmt der Eintrag, bleibt die Datei dieselbe (gleiche
    Datei-Nummer, gleiche Zeit, gleiche Bytes) — kein Schreiben bei jedem Start."""
    assert wk.startmenue_eintrag(ordner=str(tmp_path)) == "angelegt"
    pfad = tmp_path / "SyncYouTube.lnk"
    vorher = _stand(pfad)
    assert wk.startmenue_eintrag(ordner=str(tmp_path)) == "unveraendert"
    assert _stand(pfad) == vorher


def test_eigener_veralteter_eintrag_wird_nachgezogen(tmp_path):
    """Programm verschoben — das bisherige Ziel startet nicht mehr: der EIGENE
    Eintrag (erkennbar an der Kennung) zeigt danach auf den neuen Ort."""
    alt = wk.startziel(False, sys.executable, str(tmp_path / "Alter Ort" / "System"))
    assert wk.startmenue_eintrag(ordner=str(tmp_path), ziel=alt) == "angelegt"
    assert wk.startmenue_eintrag(ordner=str(tmp_path)) == "aktualisiert"
    gelesen = _windows_liest(tmp_path / "SyncYouTube.lnk")
    assert gelesen["argumente"] == wk.startziel(False, sys.executable, MODUL_DIR)["argumente"]
    assert gelesen["kennung"] == KENNUNG
    assert sorted(os.listdir(tmp_path)) == ["SyncYouTube.lnk"]


def _attrappe_exe(pfad):
    """Eine Datei, die als Startziel „da" ist (gestartet wird sie nie)."""
    pfad.parent.mkdir(parents=True, exist_ok=True)
    pfad.write_bytes(b"MZ")
    return str(pfad)


def test_eintrag_folgt_nicht_jedem_start(tmp_path):
    """Prüfung Runde 2 (mittel): Das Soll-Ziel entstand bei jedem Start aus
    sys.executable, und ein eigener Eintrag mit anderem Ziel wurde
    überschrieben — der LETZTE Start gewann. Ein einziger Start der exe (sie
    nimmt ihren eigenen Ordner als Datenordner) stellte den Eintrag auf einen
    anderen Datenbestand um, ein Start mit dem Basis-Python auf ein Python ohne
    die venv-Pakete. EINE stabile Regel: das Ziel wechselt nur, wenn das
    bisherige nicht mehr startet (Programm verschoben, exe entfernt)."""
    exe = _attrappe_exe(tmp_path / "Programm" / "SyncYouTube.exe")
    exe_ziel = wk.startziel(True, exe, MODUL_DIR)
    basis = _attrappe_exe(tmp_path / "Basis" / "python.exe")
    _attrappe_exe(tmp_path / "Basis" / "pythonw.exe")
    basis_ziel = wk.startziel(False, basis, MODUL_DIR)

    quelle = tmp_path / "quelle"
    quelle.mkdir()
    assert wk.startmenue_eintrag(ordner=str(quelle)) == "angelegt"      # Quellbetrieb (venv)
    vorher = _stand(quelle / "SyncYouTube.lnk")
    for ziel in (exe_ziel, basis_ziel):                                 # ein Start der exe, des Basis-Pythons
        assert wk.startmenue_eintrag(ordner=str(quelle), ziel=ziel) == "behalten"
        assert _stand(quelle / "SyncYouTube.lnk") == vorher, ziel["ziel"]

    umgekehrt = tmp_path / "umgekehrt"                                  # zuerst die exe: sie bleibt
    umgekehrt.mkdir()
    assert wk.startmenue_eintrag(ordner=str(umgekehrt), ziel=exe_ziel) == "angelegt"
    vorher = _stand(umgekehrt / "SyncYouTube.lnk")
    assert wk.startmenue_eintrag(ordner=str(umgekehrt)) == "behalten"
    assert _stand(umgekehrt / "SyncYouTube.lnk") == vorher

    os.remove(exe)                                                      # exe entfernt: startet nicht mehr
    assert wk.startmenue_eintrag(ordner=str(umgekehrt)) == "aktualisiert"
    gelesen = _windows_liest(umgekehrt / "SyncYouTube.lnk")
    assert os.path.normcase(gelesen["ziel"]) == os.path.normcase(_pythonw()), gelesen
    assert gelesen["kennung"] == KENNUNG
    assert wk.startmenue_eintrag(ordner=str(umgekehrt)) == "unveraendert"


def test_fremde_verknuepfung_bleibt_unberuehrt(tmp_path, monkeypatch):
    """Nie eine fremde Verknüpfung anfassen: ohne Kennung (Installer, von
    Hand), mit einer anderen Kennung, oder gar keine lesbare Verknüpfung."""
    pfad = tmp_path / "SyncYouTube.lnk"
    _fremde_verknuepfung(pfad)
    faelle = [("ohne Kennung", _stand(pfad))]
    log = []
    assert wk.startmenue_eintrag(ordner=str(tmp_path), log=log.append) == "fremd"
    assert _stand(pfad) == faelle[0][1]
    assert log and "unverändert" in log[-1], log

    anderer = tmp_path / "anders"
    anderer.mkdir()
    monkeypatch.setattr(wk, "KENNUNG", "Fremd.Programm")
    assert wk.startmenue_eintrag(ordner=str(anderer)) == "angelegt"
    monkeypatch.setattr(wk, "KENNUNG", KENNUNG)
    vorher = _stand(anderer / "SyncYouTube.lnk")
    assert _windows_liest(anderer / "SyncYouTube.lnk")["kennung"] == "Fremd.Programm"
    assert wk.startmenue_eintrag(ordner=str(anderer)) == "fremd"
    assert _stand(anderer / "SyncYouTube.lnk") == vorher

    kaputt = tmp_path / "kaputt"
    kaputt.mkdir()
    (kaputt / "SyncYouTube.lnk").write_bytes(b"keine Verknuepfung")
    assert wk.startmenue_eintrag(ordner=str(kaputt)) == "fremd"
    assert (kaputt / "SyncYouTube.lnk").read_bytes() == b"keine Verknuepfung"
    assert sorted(os.listdir(kaputt)) == ["SyncYouTube.lnk"]


def test_ohne_startbares_ziel_kein_eintrag(tmp_path):
    """Fehlt das pythonw neben dem laufenden Python, entstünde ein toter
    Eintrag — dann lieber keiner, mit Protokoll."""
    log = []
    ziel = wk.startziel(False, str(tmp_path / "gibtsnicht" / "python.exe"), MODUL_DIR)
    assert wk.startmenue_eintrag(ordner=str(tmp_path), ziel=ziel, log=log.append) == "kein_ziel"
    assert os.listdir(tmp_path) == [] and log


def test_fehler_werden_still_protokolliert(tmp_path, monkeypatch):
    log = []

    def kaputt(*a, **k):
        raise OSError("COM nicht verfügbar")
    monkeypatch.setattr(wk, "_schreiben", kaputt)
    assert wk.startmenue_eintrag(ordner=str(tmp_path), log=log.append) == "fehler"
    assert log and "COM nicht verfügbar" in log[-1]
    assert wk.startmenue_eintrag(ordner=str(tmp_path / "fehlt"), log=log.append) == "fehler"
    assert not (tmp_path / "fehlt").exists(), "fremden Ordner angelegt"


def test_im_hintergrund_eigener_faden(tmp_path):
    """faden=True blockiert den Start nicht und richtet COM im eigenen Faden ein."""
    faden = wk.startmenue_eintrag(ordner=str(tmp_path), faden=True)
    faden.join(60)
    assert not faden.is_alive() and faden.daemon
    assert _windows_liest(tmp_path / "SyncYouTube.lnk")["kennung"] == KENNUNG


# ------------------------------------------------ Einbau in den Server

def _main_knoten():
    baum = ast.parse(open(os.path.join(MODUL_DIR, "youtube_app.py"), encoding="utf-8").read())
    return baum, next(n for n in baum.body if isinstance(n, ast.FunctionDef) and n.name == "main")


def _name(call):
    f = call.func
    if isinstance(f, ast.Attribute) and isinstance(f.value, ast.Name):
        return f"{f.value.id}.{f.attr}"
    return getattr(f, "id", getattr(f, "attr", ""))


def _aufrufe(baum, name):
    """(Funktion der obersten Ebene, Aufruf-Knoten) für jeden AUFRUF von name."""
    return [(getattr(k, "name", "<Modulebene>"), n) for k in baum.body for n in ast.walk(k)
            if isinstance(n, ast.Call) and _name(n) == name]


def test_server_setzt_die_kennung_vor_jedem_fenster():
    """Microsoft: die Kennung „before the application presents any UI" setzen.
    Der Aufruf steht als eigene Anweisung direkt in main() (nicht in einem Zweig)
    und VOR Server (danach Ordner-Dialog), Browser, SMTC-Fenster und Tray.
    Ein Import von youtube_app setzt nichts."""
    baum, main = _main_knoten()
    wo = _aufrufe(baum, "windows_kennung.setze_kennung")
    assert [f for f, _ in wo] == ["main"], wo
    stelle = next((a for a in main.body if isinstance(a, ast.Expr) and a.value is wo[0][1]), None)
    assert stelle is not None, "setze_kennung() steht nicht als eigene Anweisung direkt in main()"
    spaeter = {"_smtc_einrichten", "_tray_icon", "ThreadingHTTPServer", "webbrowser.open",
               "threading.Timer", "windows_kennung.startmenue_eintrag"}
    ui = sorted((n.lineno, _name(n)) for n in ast.walk(main)
                if isinstance(n, ast.Call) and _name(n) in spaeter)
    assert {name for _, name in ui} == spaeter, f"Wächter blind: gefunden {ui}"
    assert stelle.lineno < ui[0][0], f"setze_kennung erst in Zeile {stelle.lineno}, vorher {ui[0]}"


def test_startmenue_eintrag_nur_beim_echten_start():
    """Einmal je Start, in main(), im Hintergrund (faden=True), hinter dem
    Einzel-Instanz-Riegel (nach dem Server-Bind) und NIE im Testmodus."""
    baum, main = _main_knoten()
    wo = _aufrufe(baum, "windows_kennung.startmenue_eintrag")
    assert [f for f, _ in wo] == ["main"], wo
    aufruf = wo[0][1]
    eltern = {kind: knoten for knoten in ast.walk(main) for kind in ast.iter_child_nodes(knoten)}
    knoten, zweige = aufruf, []
    while knoten in eltern:
        knoten = eltern[knoten]
        if isinstance(knoten, ast.If):
            zweige.append(ast.unparse(knoten.test))
    assert "not TESTMODUS" in zweige, f"nicht durch 'if not TESTMODUS' geschützt: {zweige}"
    assert any(k.arg == "faden" and getattr(k.value, "value", None) is True
               for k in aufruf.keywords), "blockiert den Start (faden=True fehlt)"
    bind = min(n.lineno for n in ast.walk(main)
               if isinstance(n, ast.Call) and _name(n) == "ThreadingHTTPServer")
    assert aufruf.lineno > bind, "vor dem Einzel-Instanz-Riegel: eine Zweit-Instanz schriebe mit"


def test_exe_nimmt_windows_kennung_mit(monkeypatch):
    """Die Bauvorschrift wird mit Attrappen ausgeführt: windows_kennung steht in
    den hiddenimports (JB: „auch in der exe bei Freunden")."""
    def collect_all(name):
        return ([], [], [])
    hooks = types.ModuleType("PyInstaller.utils.hooks")
    hooks.collect_all = collect_all
    for name, mod in (("PyInstaller", types.ModuleType("PyInstaller")),
                      ("PyInstaller.utils", types.ModuleType("PyInstaller.utils")),
                      ("PyInstaller.utils.hooks", hooks)):
        monkeypatch.setitem(sys.modules, name, mod)
    analyse = {}

    def Analysis(skripte, **kw):
        analyse.update(kw)
        return types.SimpleNamespace(pure=[], scripts=[], binaries=[], datas=[])
    g = {"__name__": "__spec__", "Analysis": Analysis,
         "PYZ": lambda *a, **k: None, "EXE": lambda *a, **k: None}
    spec = open(os.path.join(MODUL_DIR, "SyncYouTube.spec"), encoding="utf-8").read()
    exec(compile(spec, "SyncYouTube.spec", "exec"), g)
    assert "windows_kennung" in analyse["hiddenimports"]
